In [2]:
import pandas as pd
from src.models.model1.recommend import build_new_group_profile
from src.data.build_features_3 import build_technique_interaction_rate
from sklearn.preprocessing import StandardScaler

In [7]:
test_data = pd.read_pickle ('data/test/m06c_1_1_test_data.pkl')
group_features = pd.read_pickle ('data/processed/model1/processed_group_features.pkl')
technique_features = pd.read_pickle ('data/processed/model1/processed_technnique_features.pkl')

train_labels =pd.read_pickle ('data/processed/model1/processed_train_labels.pkl')
y_cleaned = pd.read_pickle ('data/interim/y_cleaned.pkl')


In [16]:
y_cleaned = pd.read_pickle ('data/interim/y_cleaned.pkl')
train_label_df = y_cleaned
interaction_count = train_label_df[train_label_df['label'] == 1.0]['group_ID'].value_counts()
interaction_count

group_ID
G0032    91
G0094    89
G0007    86
G0050    78
G0059    77
         ..
G0025     2
G0029     1
G0063     1
G0002     1
G0023     1
Name: count, Length: 133, dtype: int64

In [25]:
pos_y = y_cleaned[y_cleaned['label'] == 1]
counts = pos_y['group_ID'].value_counts().values.reshape (-1,1)
scaler = StandardScaler()
scaler.fit (counts)

StandardScaler()

1. Interaction rate: recalculate original (not normalized) values.

In [ ]:
group_features = build_feature_interaction_frequency (label_df= train_labels,
                                                      feature_df= group_features, 
                                                      object_ID= 'group_ID', 
                                                      feature_name = 'original_group_interaction_rate', 
                                                      normalize= False)
group_features

group_ID                            input_group_software_id  \
0      G0099                                            [other]   
1      G0006  [s0025, s0119, s0026, s0121, s0002, s0039, s01...   
2      G0005                              [s0040, s0015, s0003]   
3      G0023                                            [s0064]   
4      G0025                                            [s0069]   
..       ...                                                ...   
131    G0044                                     [s0013, other]   
132    G0102  [s0552, s0534, s0521, s0154, s0363, s0632, s00...   
133    G0128                                                 []   
134    G0018         [s0039, s0012, s0096, s0100, s0104, other]   
135    G0045  [s0552, s0154, s0357, s0002, s0039, s0097, s00...   

                               input_group_description  \
0    [-0.41692165, -0.26227784, -0.47415727, 0.0276...   
1    [-0.6153141, 0.07517785, -0.5039633, -0.243659...   
2    [-0.32223642, 0.029669948, -0.7427179, -0.0198...   
3    [-0.39972576, -0.06616345, -0.55075675, -0.038...   
4    [-0.608141, -0.007160956, -0.7598587, 0.167140...   
..                                                 ...   
131  [-0.3997315, 0.011453139, -0.5749509, -0.17962...   
132  [-0.27592593, -0.100573234, -0.37286678, -0.02...   
133  [-0.48862642, -0.18858606, -0.5323841, -0.0883...   
134  [-0.2925966, 0.0350828, -0.64397854, 0.130665,...   
135  [-0.73226637, -0.113698326, -1.0054364, -0.120...   

     input_group_interaction_rate  \
0                       -0.924954   
1                        0.105041   
2                       -0.924954   
3                       -0.924954   
4                       -0.924954   
..                            ...   
131                     -0.924954   
132                      1.135036   
133                      0.239388   
134                     -0.387565   
135                      1.179819   

                                   input_group_tactics  \
0                                                   []   
1    [discovery, resource_development, collection, ...   
2                                                   []   
3                                                   []   
4                                                   []   
..                                                 ...   
131                                                 []   
132  [discovery, collection, credential_access, com...   
133  [resource_development, resource_development, p...   
134  [discovery, execution, execution, discovery, d...   
135  [discovery, resource_development, collection, ...   

     original_group_interaction_rate  
0                                0.0  
1                               48.0  
2                                0.0  
3                                0.0  
4                                0.0  
..                               ...  
131                              0.0  
132                              0.0  
133                             54.0  
134                             24.0  
135                            115.0  

[136 rows x 6 columns]

In [ ]:
scaler = StandardScaler()
scaler.fit (group_features[['input_group_interaction_rate']])
original_values = scaler.inverse_transform(group_features[['input_group_interaction_rate']])
original_values

array([[-0.92495409],
       [ 0.10504107],
       [-0.92495409],
       [-0.92495409],
       [-0.92495409],
       [-0.38756531],
       [ 0.01547627],
       [ 2.92633216],
       [ 1.49329541],
       [ 1.00068903],
       [-0.92495409],
       [ 2.56807297],
       [ 0.46330025],
       [ 0.37373546],
       [ 1.00068903],
       [ 1.40373062],
       [ 1.7619898 ],
       [-0.92495409],
       [-0.38756531],
       [-0.92495409],
       [-0.25321812],
       [-0.20843572],
       [-0.20843572],
       [ 0.86634184],
       [-0.25321812],
       [-0.92495409],
       [-0.29800052],
       [ 0.06025867],
       [-0.92495409],
       [-0.92495409],
       [ 1.7172074 ],
       [-0.92495409],
       [ 0.59764745],
       [-0.07408853],
       [-0.92495409],
       [-0.38756531],
       [-0.92495409],
       [-0.47713011],
       [ 0.14982346],
       [-0.47713011],
       [-0.92495409],
       [ 1.58286021],
       [-0.25321812],
       [ 1.04547143],
       [-0.92495409],
       [-0

In [ ]:
scaler = StandardScaler ()
group_features ['original_group_interaction_rate'] = scaler.fit_transform (group_features[['original_group_interaction_rate']])

In [ ]:
group_features

group_ID                            input_group_software_id  \
0      G0099                                            [other]   
1      G0006  [s0025, s0119, s0026, s0121, s0002, s0039, s01...   
2      G0005                              [s0040, s0015, s0003]   
3      G0023                                            [s0064]   
4      G0025                                            [s0069]   
..       ...                                                ...   
131    G0044                                     [s0013, other]   
132    G0102  [s0552, s0534, s0521, s0154, s0363, s0632, s00...   
133    G0128                                                 []   
134    G0018         [s0039, s0012, s0096, s0100, s0104, other]   
135    G0045  [s0552, s0154, s0357, s0002, s0039, s0097, s00...   

                               input_group_description  \
0    [-0.41692165, -0.26227784, -0.47415727, 0.0276...   
1    [-0.6153141, 0.07517785, -0.5039633, -0.243659...   
2    [-0.32223642, 0.029669948, -0.7427179, -0.0198...   
3    [-0.39972576, -0.06616345, -0.55075675, -0.038...   
4    [-0.608141, -0.007160956, -0.7598587, 0.167140...   
..                                                 ...   
131  [-0.3997315, 0.011453139, -0.5749509, -0.17962...   
132  [-0.27592593, -0.100573234, -0.37286678, -0.02...   
133  [-0.48862642, -0.18858606, -0.5323841, -0.0883...   
134  [-0.2925966, 0.0350828, -0.64397854, 0.130665,...   
135  [-0.73226637, -0.113698326, -1.0054364, -0.120...   

     input_group_interaction_rate  \
0                       -0.924954   
1                        0.105041   
2                       -0.924954   
3                       -0.924954   
4                       -0.924954   
..                            ...   
131                     -0.924954   
132                      1.135036   
133                      0.239388   
134                     -0.387565   
135                      1.179819   

                                   input_group_tactics  \
0                                                   []   
1    [discovery, resource_development, collection, ...   
2                                                   []   
3                                                   []   
4                                                   []   
..                                                 ...   
131                                                 []   
132  [discovery, collection, credential_access, com...   
133  [resource_development, resource_development, p...   
134  [discovery, execution, execution, discovery, d...   
135  [discovery, resource_development, collection, ...   

     original_group_interaction_rate  
0                          -0.736860  
1                           0.256782  
2                          -0.736860  
3                          -0.736860  
4                          -0.736860  
..                               ...  
131                        -0.736860  
132                        -0.736860  
133                         0.380987  
134                        -0.240039  
135                         1.643741  

[136 rows x 6 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
import numpy as np

# Your normalized values
normalized_values = np.array([[0.5, 1.0, 1.5],
                              [2.0, 2.5, 3.0],
                              [3.5, 4.0, 4.5]])

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to your normalized data
scaler.fit(normalized_values)

# Use inverse_transform to get the original values
original_values = scaler.inverse_transform(normalized_values)

print("Original Values:")
print(original_values)


Original Values:
[[2.61237244 3.72474487 4.83711731]
 [4.44948974 5.56186218 6.67423461]
 [6.28660705 7.39897949 8.51135192]]
