In [2]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [3]:
text = "(((For all the time that you rained on my parade. For all the club you get in using my name."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

In [4]:
encoded_input

{'input_ids': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[  101,  1006,  1006,  1006,  2005,  2035,  1996,  2051,  2008,
         2017, 28270,  2006,  2026,  7700,  1012,  2005,  2035,  1996,
         2252,  2017,  2131,  1999,  2478,  2026,  2171,  1012,   102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]])>}

In [5]:
output.pooler_output

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-0.33007511, -0.32280993, -0.72437876,  0.13342477,  0.66632426,
        -0.32943666, -0.14530553,  0.32142636, -0.12383968, -0.996462  ,
        -0.18743022,  0.74094224,  0.97523755,  0.181895  ,  0.72451293,
        -0.3103287 , -0.23653689, -0.46927568,  0.19118546,  0.7876528 ,
         0.56764776,  0.99915713,  0.18697284,  0.22549418,  0.52358943,
         0.8435739 , -0.6907088 ,  0.8301848 ,  0.83409435,  0.4935151 ,
         0.03955415,  0.16123886, -0.98576236, -0.19193833, -0.81186366,
        -0.98732936,  0.17869611, -0.17670476, -0.00174551,  0.0992678 ,
        -0.807761  ,  0.4339554 ,  0.9948507 ,  0.22523947,  0.46853054,
        -0.33395064, -0.9979838 ,  0.28027216, -0.7468656 ,  0.11620659,
         0.60454404,  0.6046788 , -0.06326352,  0.28187203,  0.50535434,
         0.07443479, -0.05250134,  0.06171548, -0.09933703, -0.59023887,
        -0.55607784,  0.41957265, -0.64465153, -0.62544143,  0.740814  ,
 

In [6]:
import tensorflow as tf
last_hidden_state = output.last_hidden_state
# Calculate the mean of the hidden states along the sequence dimension
sentence_embedding = tf.math.reduce_mean(last_hidden_state, axis=1)

In [7]:
last_hidden_state.shape

TensorShape([1, 27, 768])

In [8]:
sentence_embedding

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 1.32163212e-01,  1.05201609e-01,  2.86737233e-01,
        -5.28352618e-01, -1.75250620e-01,  1.01241313e-01,
         3.30285311e-01,  9.47840095e-01, -4.07989889e-01,
         2.30622873e-01,  4.27954793e-01, -3.28010023e-01,
        -2.36772627e-01,  3.46462019e-02, -1.05849445e-01,
         3.46531302e-01,  2.17460275e-01,  1.40056297e-01,
        -3.86431850e-02,  1.43428624e-01,  4.16473329e-01,
         4.22572702e-01, -1.95134237e-01,  3.52260768e-01,
         6.40255883e-02,  1.25198252e-02, -4.50537726e-02,
         1.89241618e-01, -3.84721369e-01, -4.46125299e-01,
         1.84403971e-01,  8.66059363e-02, -1.01287507e-01,
         9.74736735e-02,  4.95604575e-02, -1.33931741e-01,
         1.13297850e-01, -1.11572318e-01, -3.09083581e-01,
         3.35202217e-01, -5.98470569e-01,  1.58872440e-01,
         6.48410395e-02,  5.71198910e-02, -2.27413565e-01,
        -3.42764229e-01,  6.98437989e-01,  2.57945736e-04,
      

In [9]:
import pandas as pd
from transformers import BertTokenizer, TFBertModel
import tensorflow as tf

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained('bert-base-uncased')

# Function to embed sentences
def embed_sentence(sentence):
    tokens = tokenizer(sentence, padding=True, truncation=True, return_tensors='tf')
    outputs = model(tokens)
    return outputs.last_hidden_state[:, 0, :]

# Read your DataFrame with a column named 'sentences'
# Replace 'your_dataframe.csv' with your actual file and path
df = pd.read_pickle('data/interim/X_group_org.pkl')

# Embed the 'sentences' column and create a new column 'bert_embedding'
df['bert_embedding'] = df['input_group_description'].apply(embed_sentence)

# Save the DataFrame with embeddings to a new CSV file
# Replace 'output_dataframe.csv' with your desired file and path
# df.to_csv('output_dataframe.csv', index=False)


Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [16]:
(df['bert_embedding'].iloc[0])

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-4.16921645e-01, -2.62277842e-01, -4.74157274e-01,
         2.76676770e-02, -1.35153055e-01,  1.14857748e-01,
         1.47445485e-01,  4.89269555e-01,  1.86809115e-02,
         4.15568531e-01, -1.33913934e-01, -5.25618494e-01,
        -7.19563603e-01,  5.54687321e-01, -1.97921947e-01,
        -1.34151652e-01,  1.42344400e-01,  3.41157168e-01,
         6.55924380e-01,  3.68389785e-01, -2.33491659e-01,
        -3.73971999e-01,  5.75947285e-01, -2.66699493e-02,
        -2.87965953e-01,  9.18158069e-02, -1.20751441e-01,
         3.52291316e-02,  4.03808236e-01, -2.51427203e-01,
         1.85513109e-01, -9.70685631e-02,  8.19100440e-02,
        -5.20841241e-01,  1.02357484e-01,  2.79216170e-01,
        -1.54126987e-01, -4.66625929e-01, -1.52747296e-02,
         2.47648120e-01, -4.35374945e-01, -1.35729820e-01,
        -1.82826459e-01,  3.88479292e-01, -4.19388711e-03,
        -1.63498163e-01, -3.20342231e+00,  1.78082377e-01,
      