In [1]:
import pandas as pd
import tensorflow as tf

# Example DataFrame with float columns
data = {
    'column_1': [1.0, 2.0, 3.0, 4.0],
    'column_2': [5.0, 6.0, 7.0, 8.0],
    'column_3': [9.0, 10.0, 11.0, 12.0]
}

df = pd.DataFrame(data)

# Convert DataFrame columns to TensorFlow tensors
tensor_column_1 = tf.constant(df['column_1'].values, dtype=tf.float32)
tensor_column_2 = tf.constant(df['column_2'].values, dtype=tf.float32)
tensor_column_3 = tf.constant(df['column_3'].values, dtype=tf.float32)

# Create a TensorFlow dataset
dataset = tf.data.Dataset.from_tensor_slices((tensor_column_1, tensor_column_2, tensor_column_3))

# Optional: You can shuffle, batch, repeat, etc., the dataset as needed for training
# dataset = dataset.shuffle(buffer_size).batch(batch_size).repeat(num_epochs)

# Example: Iterate through the dataset
for example in dataset:
    print(example)


(<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=5.0>, <tf.Tensor: shape=(), dtype=float32, numpy=9.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=2.0>, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>, <tf.Tensor: shape=(), dtype=float32, numpy=10.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>, <tf.Tensor: shape=(), dtype=float32, numpy=7.0>, <tf.Tensor: shape=(), dtype=float32, numpy=11.0>)
(<tf.Tensor: shape=(), dtype=float32, numpy=4.0>, <tf.Tensor: shape=(), dtype=float32, numpy=8.0>, <tf.Tensor: shape=(), dtype=float32, numpy=12.0>)
