In [1]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = TFBertModel.from_pretrained("bert-base-uncased")
text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [2]:
text = "(((For all the time that you rained on my parade. For all the club you get in using my name."
encoded_input = tokenizer(text, return_tensors='tf')
output = model(encoded_input)

In [3]:
encoded_input

{'input_ids': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[  101,  1006,  1006,  1006,  2005,  2035,  1996,  2051,  2008,
         2017, 28270,  2006,  2026,  7700,  1012,  2005,  2035,  1996,
         2252,  2017,  2131,  1999,  2478,  2026,  2171,  1012,   102]])>, 'token_type_ids': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0]])>, 'attention_mask': <tf.Tensor: shape=(1, 27), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1]])>}

In [4]:
output.pooler_output

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-8.36234450e-01, -4.84139860e-01, -8.65592241e-01,
         6.96143270e-01,  8.53051066e-01, -1.16731443e-01,
         5.99135995e-01,  1.71558976e-01, -7.86886275e-01,
        -9.99927640e-01, -5.27536571e-01,  9.66243565e-01,
         9.81256545e-01,  4.81545448e-01,  8.94074559e-01,
        -6.81626141e-01, -2.85233319e-01, -5.59600115e-01,
         2.67194778e-01,  3.61705989e-01,  6.26397371e-01,
         9.99957085e-01, -2.43028924e-02,  2.24717185e-01,
         4.52240258e-01,  9.91178334e-01, -6.72679245e-01,
         9.15873230e-01,  9.44308579e-01,  6.09080732e-01,
        -3.23860168e-01,  3.20632569e-02, -9.92476881e-01,
        -4.52369563e-02, -8.51619601e-01, -9.90570307e-01,
         4.13175642e-01, -5.68134308e-01,  4.18954879e-01,
         1.21566243e-01, -8.81798387e-01,  2.61017472e-01,
         9.99947667e-01,  2.03859910e-01,  4.77537245e-01,
        -1.59036070e-01, -9.99999225e-01,  2.04293892e-01,
      

In [5]:
import tensorflow as tf
last_hidden_state = output.last_hidden_state
# Calculate the mean of the hidden states along the sequence dimension
sentence_embedding = tf.math.reduce_mean(last_hidden_state, axis=1)

In [6]:
last_hidden_state.shape

TensorShape([1, 24, 768])

In [4]:
sentence_embedding

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 3.09511393e-01, -1.06642254e-01,  2.04236805e-01,
        -7.70857856e-02, -1.31926447e-01, -3.98896456e-01,
         2.92962879e-01,  9.01827991e-01,  1.65985718e-01,
        -1.77534565e-01, -8.09586048e-02, -3.52362156e-01,
        -2.58860499e-01,  1.55083135e-01, -5.12036324e-01,
         2.89578170e-01, -4.62743193e-01,  1.97618917e-01,
        -2.76635051e-01,  3.10678244e-01, -8.86487141e-02,
         2.39159063e-01, -2.31419623e-01, -1.44697474e-02,
         5.31469941e-01,  1.24729872e-01, -2.03199372e-01,
        -4.60857302e-02, -2.79241234e-01, -5.36349952e-01,
         4.43058401e-01,  3.53755325e-01, -2.22629949e-01,
        -3.49393726e-04, -5.51930368e-02, -1.46235839e-01,
         2.86361784e-01, -1.27637550e-01, -6.12481356e-01,
         9.59208310e-02, -7.64012039e-01, -2.88058847e-01,
         1.38505220e-01,  3.00815165e-01,  2.25185648e-01,
        -5.34832060e-01,  2.15904534e-01,  2.46484593e-01,
      