In [162]:
import tensorflow as tf
import pandas as pd

In [171]:
t = pd.read_pickle ('data/interim/X_technique.pkl')
t_vocab = pd.read_csv ('data/interim/input_technique_mitigation_id_vocab.csv', header= None)[0].dropna().values

In [172]:
t

technique_ID input_technique_platforms  \
0          T1548   [linux, windows, macos]   
1      T1548.002                 [windows]   
2      T1548.004                   [macos]   
3      T1548.001            [linux, macos]   
4      T1548.003            [linux, macos]   
..           ...                       ...   
602    T1102.002   [linux, windows, macos]   
603    T1102.001   [linux, windows, macos]   
604    T1102.003   [linux, windows, macos]   
605        T1047                 [windows]   
606        T1220                 [windows]   

                     input_technique_tactics  \
0    [defense_evasion, privilege_escalation]   
1    [defense_evasion, privilege_escalation]   
2    [defense_evasion, privilege_escalation]   
3    [defense_evasion, privilege_escalation]   
4    [defense_evasion, privilege_escalation]   
..                                       ...   
602                    [command_and_control]   
603                    [command_and_control]   
604                    [command_and_control]   
605                              [execution]   
606                        [defense_evasion]   

                          input_technique_data_sources  \
0    [command_command_execution, file_file_metadata...   
1    [command_command_execution, process_process_cr...   
2    [process_os_api_execution, process_process_cre...   
3    [command_command_execution, file_file_metadata...   
4    [command_command_execution, file_file_modifica...   
..                                                 ...   
602  [network_traffic_network_connection_creation, ...   
603  [network_traffic_network_traffic_content, netw...   
604  [network_traffic_network_connection_creation, ...   
605  [command_command_execution, network_traffic_ne...   
606     [module_module_load, process_process_creation]   

                     input_technique_defenses_bypassed  \
0                                                   []   
1                       [windows_user_account_control]   
2                                                   []   
3                                                   []   
4                                                   []   
..                                                 ...   
602                                                 []   
603                                                 []   
604                                                 []   
605                                                 []   
606  [anti_virus, application_control, digital_cert...   

    input_technique_permissions_required  \
0                  [administrator, user]   
1                  [administrator, user]   
2                  [administrator, user]   
3                                 [user]   
4                                 [user]   
..                                   ...   
602                               [user]   
603                               [user]   
604                               [user]   
605                                   []   
606                                   []   

                  input_technique_mitigation_id  \
0    [m1047, m1038, m1028, m1026, m1022, m1052]   
1                  [m1047, m1026, m1051, m1052]   
2                                       [m1038]   
3                                       [m1028]   
4                         [m1028, m1026, m1022]   
..                                          ...   
602                              [m1031, m1021]   
603                              [m1031, m1021]   
604                              [m1031, m1021]   
605                [m1040, m1038, m1026, m1018]   
606                                     [m1038]   

                        input_technique_detection_name  \
0    [command_execution, file_metadata, file_modifi...   
1    [command_execution, process_creation, process_...   
2                 [os_api_execution, process_creation]   
3    [command_execution, file_metadata, file_modifi...   
4    [command_execution, file_modification, proc

In [173]:
t_vocab

array(['m1047', 'm1038', 'm1028', 'm1026', 'm1022', 'm1018', 'm1032',
       'm1030', 'm1042', 'm1056', 'm1037', 'm1031', 'm1017', 'm1027',
       'm1040'], dtype=object)

In [174]:
tf_vectorize = tf.keras.layers.TextVectorization (
    max_tokens=1000,
    output_mode = 'int', 
    output_sequence_length = None,
    split = None, 
    vocabulary = t_vocab
)
tf_embed = tf.keras.layers.Embedding (input_dim = 2 + len(t_vocab),       input_length= None,    output_dim=5, mask_zero= True)

In [180]:
for i in range (1,100, 13):
    data = t['input_technique_mitigation_id'].iloc[i]
    print (data)
    data = tf_vectorize(data)
    # print (data)
    data = tf_embed (data)
    # print (data)
    data = tf.reduce_mean(data,axis=0)
    print (data)

['m1047', 'm1026', 'm1051', 'm1052']
tf.Tensor([ 0.0058594   0.00322477 -0.00580804  0.00654894 -0.003473  ], shape=(5,), dtype=float32)
['m1028']
tf.Tensor([-0.0084356  -0.01719754  0.04135385  0.02067164 -0.04650582], shape=(5,), dtype=float32)
['m1056']
tf.Tensor([-0.02562091 -0.03698369 -0.03841227 -0.02691079 -0.03466545], shape=(5,), dtype=float32)
['m1042', 'm1037', 'm1031', 'm1030']
tf.Tensor([-0.01085484 -0.00257254  0.00229212 -0.00738375 -0.00475142], shape=(5,), dtype=float32)
['']
tf.Tensor([-0.04872457  0.02306     0.03147249  0.02304551 -0.04967315], shape=(5,), dtype=float32)
['m1025']
tf.Tensor([ 0.02497728  0.03658276 -0.04019512 -0.00747579 -0.01593764], shape=(5,), dtype=float32)
['m1018', 'm1017']
tf.Tensor([ 0.00103183 -0.01437488  0.02134225  0.03166806  0.00374992], shape=(5,), dtype=float32)
['m1049', 'm1040', 'm1045', 'm1042', 'm1038', 'm1026', 'm1021']
tf.Tensor([ 0.00638311  0.02680011 -0.01661375  0.00133438 -0.0076843 ], shape=(5,), dtype=float32)


In [181]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

# Example data: multiple lists of strings for each instance
data = [
    [["This is sentence one"], ["Another sentence"]],
    [["Example for demonstration"], ["Text vectorization"]]
]

# Initialize TextVectorization layer
vectorizer = TextVectorization(max_tokens=1000, output_mode='int', output_sequence_length=10)

# Adapt the layer to the text data
flat_data = [string for sublist in data for string in sublist]  # Flatten the nested lists
vectorizer.adapt(flat_data)

# Custom Keras model
class CustomModel(tf.keras.Model):
    def __init__(self, vectorizer, embedding_dim):
        super(CustomModel, self).__init__()
        self.vectorizer = vectorizer
        self.embedding = tf.keras.layers.Embedding(input_dim=len(vectorizer.get_vocabulary()), 
                                                   output_dim=embedding_dim)
        
    def call(self, inputs):
        # Vectorize the input strings
        vectorized = [self.vectorizer(instance) for instance in inputs]
        
        # Embed the vectorized tokens
        embedded = [self.embedding(instance) for instance in vectorized]
        
        # Perform element-wise averaging across tokens
        averaged = [tf.reduce_mean(embed, axis=1) for embed in embedded]
        
        # Concatenate the result vectors side by side
        concatenated = tf.concat(averaged, axis=1)
        
        return concatenated

# Instantiate the custom model
embedding_dim = 50  # Dimensionality of the embedding
model = CustomModel(vectorizer, embedding_dim)

# Test the model with example data
test_input = [
    ["Test sentence for model"], 
    ["Another test sentence"]
]
output = model(test_input)

print("Output shape after concatenation:")
print(output.shape)


Output shape after concatenation:
(1, 100)
